batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202303301424
train_epochs: 1000
train_workers: 20
vocab: uqHEnjBY,g4NU?hWM*5PX!&.+t92L(v8IzF#A-"eoV:lCQwmd)0RKJp7'f/siTSakbrOZ1;36DcGyx
width: 128
